- name: Create user in all server
  hosts: all
  become: true
  vars:
    user_names:
      - 'eduardo'
      - 'rodolfo'
      - 'alejandro'
  tasks:
    - name: Remove Users
      user:
        name: '{{ item }}'
        state: absent
        remove: yes
      loop: "{{ user_names }}"
